### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by XiGuaSZ** [osmcode/experimental-osm-db#1]
fatal error: leveldb/db.h: No such file or directory compilation terminated.

@springmeyer @joto @lonvia

**Comment by joto** [comment]
You'll need to install https://github.com/google/leveldb .

Please don't add unrelated people to the issue. Interested people will be subscribed to this repository, everybody else should not be bothered.

**Comment by XiGuaSZ** [comment]
sorry for bothered everybody,thanks for your reply. I had install leveldb,had resolution leveldb errors.
there is a new error:
eodb_create.cpp:68:5: error: redefinition of ‘const bool osmium::index::detail::registered_dense_file_array’

**Comment by joto** [comment]
I have pushed a few changes. Please try again.

**Comment by XiGuaSZ** [comment]
No errors now.close.
